-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 17:25:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mocchiakhoa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mocchiakhoa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mocchiakhoa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mocchiakhoa` ;

-- -----------------------------------------------------
-- Table `mocchiakhoa`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`brand` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`color` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `create_date` DATE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `updated_date` DATE NULL DEFAULT NULL,
  `id_brand` BIGINT NULL DEFAULT NULL,
  `id_category` BIGINT NULL DEFAULT NULL,
  `id_color` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK55evcjddwhtr4pbaggns9nqc8` (`id_brand` ASC) VISIBLE,
  INDEX `FK5cxv31vuhc7v32omftlxa8k3c` (`id_category` ASC) VISIBLE,
  INDEX `FKgt3knpl36en2iv1tpdaj6msui` (`id_color` ASC) VISIBLE,
  CONSTRAINT `FK55evcjddwhtr4pbaggns9nqc8`
    FOREIGN KEY (`id_brand`)
    REFERENCES `mocchiakhoa`.`brand` (`id`),
  CONSTRAINT `FK5cxv31vuhc7v32omftlxa8k3c`
    FOREIGN KEY (`id_category`)
    REFERENCES `mocchiakhoa`.`category` (`id`),
  CONSTRAINT `FKgt3knpl36en2iv1tpdaj6msui`
    FOREIGN KEY (`id_color`)
    REFERENCES `mocchiakhoa`.`color` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quantity_buy` INT NULL DEFAULT NULL,
  `id_product` BIGINT NULL DEFAULT NULL,
  `id_user` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK248uajx6di85sc1oj4q17ksuo` (`id_product` ASC) VISIBLE,
  INDEX `FKikbqppvx730nfh1pu7av14wr3` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK248uajx6di85sc1oj4q17ksuo`
    FOREIGN KEY (`id_product`)
    REFERENCES `mocchiakhoa`.`product` (`id`),
  CONSTRAINT `FKikbqppvx730nfh1pu7av14wr3`
    FOREIGN KEY (`id_user`)
    REFERENCES `mocchiakhoa`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `create_date` DATE NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `total_money` DOUBLE NULL DEFAULT NULL,
  `update_date` DATE NULL DEFAULT NULL,
  `id_user` BIGINT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp1jglhdt6fpf5plvbns0gp5ns` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FKp1jglhdt6fpf5plvbns0gp5ns`
    FOREIGN KEY (`id_user`)
    REFERENCES `mocchiakhoa`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`orders_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`orders_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATE NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `id_orders` BIGINT NULL DEFAULT NULL,
  `id_product` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKnp4t4vx7n73prkpt3n85uxc08` (`id_orders` ASC) VISIBLE,
  INDEX `FKqjekvibem9ip0qkj30fox87if` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FKnp4t4vx7n73prkpt3n85uxc08`
    FOREIGN KEY (`id_orders`)
    REFERENCES `mocchiakhoa`.`orders` (`id`),
  CONSTRAINT `FKqjekvibem9ip0qkj30fox87if`
    FOREIGN KEY (`id_product`)
    REFERENCES `mocchiakhoa`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mocchiakhoa`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mocchiakhoa`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `mocchiakhoa`.`user` (`id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `mocchiakhoa`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
